# Generated by Django 6.0.3 on 2026-09-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_service_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_created', 'Booking created'), ('booking_confirmed', 'Booking confirmed'), ('booking_rejected', 'Booking rejected'), ('booking_cancelled', 'Booking cancelled'), ('booking_rescheduled', 'Booking rescheduled')], default='booking_created', max_length=30),
        ),
    ]
