# Generated by Django 6.0.3 on 2026-09-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_business_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='availability',
            field=models.JSONField(blank=True, default=list, help_text='[{"date": "YYYY-MM-DD", "times": ["HH:MM", ...]}]. Empty list = bookable within the business working hours.'),
        ),
    ]
