# Generated by Django 6.0.3 on 2026-09-29 15:45

from decimal import Decimal

from django.db import migrations, models

CENT = Decimal("0.01")


def backfill_items(apps, schema_editor):
    """
    Existing bookings get their order composition from the booked service and
    attached products (quantity 1 each). total_price is left as it was charged.

    Only total_price records what was actually paid; prices may have changed
    since. Product lines use the current product prices, and the service line
    gets the rest of the charged total (total_price minus the product lines),
    so the lines add up to total_price. When that rest would be negative
    (products got more expensive), the current service price is used instead.
    """
    Booking = apps.get_model("core", "Booking")

    # The column was just added, so every row still has the empty default
    bookings = Booking.objects.select_related("service").prefetch_related("products")

    for booking in bookings.iterator(chunk_size=500):
        products = [
            {
                "id": product.id,
                "name": product.name,
                "price": product.price.quantize(CENT),
                "quantity": 1,
                "kind": "product",
            }
            for product in booking.products.all()
        ]

        service_price = (booking.total_price or Decimal("0")) - sum(
            (line["price"] for line in products), Decimal("0")
        )
        if service_price < 0:
            service_price = booking.service.price

        items = [{
            "id": booking.service_id,
            "name": booking.service.title,
            "price": service_price.quantize(CENT),
            "quantity": 1,
            "kind": "service",
        }] + products

        # Stored like new bookings: prices as decimal strings
        for line in items:
            line["price"] = str(line["price"])

        booking.items = items
        booking.save(update_fields=["items"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_service_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(backfill_items, migrations.RunPython.noop),
    ]
