# Generated by Django 6.0.3 on 2026-09-29 15:48

from django.db import migrations, models


def number_existing_images(apps, schema_editor):
    """
    Keep the order the gallery was shown in before (newest first):
    0 for the newest image of each business, then 1, 2, ...
    """
    BusinessGallery = apps.get_model("core", "BusinessGallery")

    position = {}
    for image in BusinessGallery.objects.order_by("business_id", "-created_at", "-id"):
        image.sort_order = position.get(image.business_id, 0)
        position[image.business_id] = image.sort_order + 1
        image.save(update_fields=["sort_order"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_notification_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessgallery',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='businessgallery',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(number_existing_images, migrations.RunPython.noop),
    ]
